name: Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  test:
    name: ⚡ Test
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 📥 Install deps
        run: npm ci --no-audit

      - name: 🧪 Test
        run: npm run test
